### ISSUE TITLE
Regarding Tri-oriented Mamba(ToM)

### ISSUE THREAD

**Issue by HashmatShadab** [ge-xing/SegMamba#11]
https://github.com/ge-xing/SegMamba/blob/a19a68b74c4f20f907f17886953471aeb38c2ed9/mamba/mamba_ssm/modules/mamba_simple.py#L180C9-L226C18

From the above lines of code, I am only able to figure out the forward and reverse direction sequences in the ToM block. Can you please point out where the inter-slice sequence is implemented.?

**Comment by ge-xing** [comment]
Hi, thank you for your attention. I haven't updated this section. I will update it recently.

**Comment by HashmatShadab** [comment]
Thanks! Kindly mention that in the readme as well.

**Comment by HashmatShadab** [comment]
Any update on when the code will be updated?

**Comment by ge-xing** [comment]
I will update the code if the paper is accepted. But if you want to try it, you can send me your email and I will send you this code.

**Comment by HashmatShadab** [comment]
hashmat.shadab.malik@gmail.com

Thanks!

**Comment by FengheTan9** [comment]
> I will update the code if the paper is accepted. But if you want to try it, you can send me your email and I will send you this code.

same issue: fhtan9@mail.ustc.edu.cn thx!

**Comment by vshy-dream** [comment]
> I will update the code if the paper is accepted. But if you want to try it, you can send me your email and I will send you this code.

same issue: vhaoyuanshi@163.com

**Comment by guohahah** [comment]
> I will update the code if the paper is accepted. But if you want to try it, you can send me your email and I will send you this code.

same issue：zhangguozxz@126.com
I want to try the code and thanks very much for your work!

**Comment by ge-xing** [comment]
I have updated my code. You can re-clone this repo.
