### ISSUE TITLE
师兄您好，有一个输出的疑问

### ISSUE THREAD

**Issue by a987042035** [ge-xing/SegMamba#12]
师兄你好，估计您的代码按nnunet构建的，想向您了解一下在训练中每轮输出的三个dice，是脑胶质瘤的wt、et、tc分别的dice分数吗，我data.json中的label是这么构建的
![图片](https://github.com/ge-xing/SegMamba/assets/48388542/baff53ff-28a1-4343-b6e8-ba9da9619dd2)
![RH7%`SN5XS35 GW4L)6X`K1](https://github.com/ge-xing/SegMamba/assets/48388542/34d91746-fcf9-440b-895b-8c4203f9b8d8)

**Comment by a987042035** [comment]
师兄还想问下您，下面的EMA pseudo Dice又是什么

**Comment by a987042035** [comment]
@ge-xing

**Comment by ge-xing** [comment]
我没有开源训练代码，你是用nnunet跑的吗？ 这个pseudo dice指的是 在nnunet里面，每次验证并不是验证全部数据，而是随机选取一些batch进行验证，因此算出来的dice指标并不是真实的。

这种方式的话，因为不需要滑动窗口进行推理，因此验证速度特别快。

**Comment by a987042035** [comment]
> 我没有开源训练代码，你是用nnunet跑的吗？ 这个pseudo dice指的是 在nnunet里面，每次验证并不是验证全部数据，而是随机选取一些batch进行验证，因此算出来的dice指标并不是真实的。
> 
> 这种方式的话，因为不需要滑动窗口进行推理，因此验证速度特别快。

谢谢师兄回答，是的师兄，我用nnunetv2构建的，师兄麻烦您看一下我构建的那个json文件，我是那么标志三个区域的，那我每轮输出的三个dice，是脑胶质瘤的wt、et、tc分别的dice分数吗，我看了半天源代码，好像又并不是这么回事，不太懂了，那在您的论文中三个区域的dice和hd95怎么计算出来的，谢谢您的回答！

**Comment by ge-xing** [comment]
我觉得你的json文件没有问题，这个是我的代码，跟你应该是一致的。

```
def convert_labels(self, labels):
        ## TC, WT and ET
        result = [(labels == 1) | (labels == 3), (labels == 1) | (labels == 3) | (labels == 2), labels == 3]
        
        return torch.cat(result, dim=1).float()
```

**Comment by ge-xing** [comment]
但是你输出的三个dice是不是对应的wt et 跟 tc 这个我就不能确定了。 也可能是对应的 1 2 3标签。 这个你得再确认下。

**Comment by a987042035** [comment]
> 但是你输出的三个dice是不是对应的wt et 跟 tc 这个我就不能确定了。 也可能是对应的 1 2 3标签。 这个你得再确认下。

谢谢师兄解答，这块看的太懵了，我用nnunet除了改了数据集和data.json文件中的东西，剩下的都是默认的了，他理论上输出的应该是我改的label三个区域吧？或者我应该去哪确认一下，源码看了半天头皮发麻

**Comment by ge-xing** [comment]
理论上是的  你可以去预处理的部分确认下，看看处理的时候是不是把3个label转换到对应的3个区域。

**Comment by a987042035** [comment]
> 理论上是的 你可以去预处理的部分确认下，看看处理的时候是不是把3个label转换到对应的3个区域。

好的师兄，谢谢师兄解答，祝您生活愉快 科研顺利！
