### ISSUE TITLE
Latest commit: "ToM" cannot run

### ISSUE THREAD

**Issue by mayaKipGal** [ge-xing/SegMamba#13]
Hi,

I tried using the latest commit (after previous version works on my machine) and it has some problems running.

Are you planning a fix anytime soon?

Thanks,

Maya

**Comment by ge-xing** [comment]
What are the problems?

**Comment by ge-xing** [comment]
Mybe you need to re-compile the Mamba module?

**Comment by mayaKipGal** [comment]
The first problem is that there is no argument nframes defined in class Mamba but when you initialize a Mamba instance in MambaLayer you try to give it as an argument.
See code below :
***@***.***


***@***.***

**Comment by ge-xing** [comment]
Thank you. I have fixed it.
