### ISSUE TITLE
Where is self.slice_attns intialized?

### ISSUE THREAD

**Issue by HashmatShadab** [ge-xing/SegMamba#14]
https://github.com/ge-xing/SegMamba/blob/1d4a213cde79e8b8e660bcbdee8f247a65e4e4cd/model_segmamba/segmamba.py#L161

**Comment by ge-xing** [comment]
Sorry, there is an inappropriate naming. I will fix it.

The slice_attn should be gsc module.

<img width="667" alt="image" src="https://github.com/ge-xing/SegMamba/assets/109211094/fc7c1831-fd1b-4a61-8517-1870dcd7a50f">

**Comment by ge-xing** [comment]
I have fixed and tested it. Thank you very much!
