### ISSUE TITLE
Regarding Model Initialization

### ISSUE THREAD

**Issue by AntiMatter568** [ge-xing/SegMamba#17]
In the `SegMamba` model initialization, the `MambaEncoder` only accepts the in_chans parameter. The `depths, feat_size, drop_path_rate, layer_scale_init_value, out_indices` are ignored. Is this intentional?

**Comment by ge-xing** [comment]
The depths, feat_size, drop_path_rate, layer_scale_init_value, and out_indices have their default value. And you can also modify them to get a larger or smaller model.

**Comment by ge-xing** [comment]
I see. I will correct this section now. Thank you~
