### ISSUE TITLE
线程问题

### ISSUE THREAD

**Issue by NetfriendT** [ge-xing/SegMamba#35]
![1dd7d4c19b7aa5e4f8e8835ccd3caf1](https://github.com/ge-xing/SegMamba/assets/171776643/37b01411-b723-401f-acc7-8d58428063ba)
![297d574afdb0e42db35a34d7cb87364](https://github.com/ge-xing/SegMamba/assets/171776643/df309cf8-6cd3-4676-8b1a-8836f386b687)
![aba5f94b33941ab506c81ac7237d5d0](https://github.com/ge-xing/SegMamba/assets/171776643/0eecdd4c-1796-4f44-a542-dd55ae40a209)
![d865c29c2ee1ce08b51eba5225063c0](https://github.com/ge-xing/SegMamba/assets/171776643/aee6e34f-0dc9-4151-b677-13f1652162ff)
![dcb2999ac1b31616d1f216ec7826b16](https://github.com/ge-xing/SegMamba/assets/171776643/df72afd4-e419-45a5-85bd-32544812752b)
师兄您好，我在跑您的segmamba代码时，跑完了到最后一点的时候报错了，显示如下，但是他也正常保存权重文件，我之后又拿这个权重文件去跑了predict，分割结果也有，但是无法覆盖在原图像上，并且尺寸也不一样，原图像时240*240*155，分割结果的尺寸是240*155*3，请问这是哪里出错了呢，是因为我的服务器的显卡不太行吗，导致后台工作线程终止

**Comment by ge-xing** [comment]
<img width="777" alt="image" src="https://github.com/ge-xing/SegMamba/assets/109211094/e12b64a9-0fc1-448e-83e2-8fab73d8e518">
https://github.com/ge-xing/SegMamba/blob/main/4_predict.py
尺寸不一样的话，你找下这个代码，本身预测出来是crop黑色背景之后的结果，这行代码是去把黑色背景填充起来，填充后应该尺寸就一致了，你可以在这代码附近打印下shape，看看运行前的尺寸跟运行后尺寸的差异。

**Comment by NetfriendT** [comment]
好的我会尝试，感谢师兄指导，另外我想再请教一下线程问题应该怎么处理呢？我服务器申请的显卡是RTX3090 24G版本，请问是有可能是显卡的问题吗

**Comment by NetfriendT** [comment]
我是否应该减少一些数据集去训练呢

**Comment by ge-xing** [comment]
https://github.com/ge-xing/SegMamba/blob/main/3_train.py#L50

这里线程数目前设置的是18，你可以减小到比如12 看看还报错不。

**Comment by ge-xing** [comment]
我觉得是没啥问题 你模型都保存了，后面的尺寸问题跟线程关系不大。

**Comment by NetfriendT** [comment]
好的，感谢师兄的指导

**Comment by princerice** [comment]
> ![1dd7d4c19b7aa5e4f8e8835ccd3caf1](https://private-user-images.githubusercontent.com/171776643/337071860-37b01411-b723-401f-acc7-8d58428063ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0MTM5MjcsIm5iZiI6MTcxODQxMzYyNywicGF0aCI6Ii8xNzE3NzY2NDMvMzM3MDcxODYwLTM3YjAxNDExLWI3MjMtNDAxZi1hY2M3LThkNTg0MjgwNjNiYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNVQwMTA3MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OGI1N2Q2YmJiYmQ4OGRmNjRmOWZjMTU3NTZmM2VkNzk3NDM0MDg4M2ZhMzY1NzZjYzQ1ZmE3OTg1YTFjZjUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LkD3ljpxbWg9p5XbxXpUifk9-ro_w5OGqk-9ujlX6E4) ![297d574afdb0e42db35a34d7cb87364](https://private-user-images.githubusercontent.com/171776643/337071865-df309cf8-6cd3-4676-8b1a-8836f386b687.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0MTM5MjcsIm5iZiI6MTcxODQxMzYyNywicGF0aCI6Ii8xNzE3NzY2NDMvMzM3MDcxODY1LWRmMzA5Y2Y4LTZjZDMtNDY3Ni04YjFhLTg4MzZmMzg2YjY4Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNVQwMTA3MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMmU5YjIzOGFkODZhYWVlNGYwMzFlYjA5NDQxNjM0Yzc2YTk3ODllYzY1NTYzNWIyMzk4Y2U1NGM5ZjBmOTYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.l2IEt_1XO-t4ob9kw00j8Pjq5JBcwB6dj9j8wpD-KCM) ![aba5f94b33941ab506c81ac7237d5d0](https://private-user-images.githubusercontent.com/171776643/337071868-0eecdd4c-1796-4f44-a542-dd55ae40a209.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0MTM5MjcsIm5iZiI6MTcxODQxMzYyNywicGF0aCI6Ii8xNzE3NzY2NDMvMzM3MDcxODY4LTBlZWNkZDRjLTE3OTYtNGY0NC1hNTQyLWRkNTVhZTQwYTIwOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNVQwMTA3MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOWUwOWRmMmM2YWRmZGVkMmUxMDg2ZGUwODQ5OGM3MjdkNTIxMDVjODRkZWY0OTU1MDkwNGM3NGI2NzRjYTA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.h5_N36DG1vjjNgZa0__2mDuryvdBGBVQYmUznA__6I8) ![d865c29c2ee1ce08b51eba5225063c0](https://private-user-images.githubusercontent.com/171776643/337071871-aee6e34f-0dc9-4151-b677-13f1652162ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0MTM5MjcsIm5iZiI6MTcxODQxMzYyNywicGF0aCI6Ii8xNzE3NzY2NDMvMzM3MDcxODcxLWFlZTZlMzRmLTBkYzktNDE1MS1iNjc3LTEzZjE2NTIxNjJmZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNVQwMTA3MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNjJiOWNjZjk0YzQ1OGFiNDAwNTY0NTcwMjVhMWNkZGM5NDA4MzYzNTYwMmFiY2EwZTRlM2ZjMTQ1Njg1NmNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.m4u1JmffbNIzUIJRA_JTHBk-qL-RIBAD6JLLRENTyx4) ![dcb2999ac1b31616d1f216ec7826b16](https://private-user-images.githubusercontent.com/171776643/337071873-df72afd4-e419-45a5-85bd-32544812752b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0MTM5MjcsIm5iZiI6MTcxODQxMzYyNywicGF0aCI6Ii8xNzE3NzY2NDMvMzM3MDcxODczLWRmNzJhZmQ0LWU0MTktNDVhNS04NWJkLTMyNTQ0ODEyNzUyYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNVQwMTA3MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NWZjMDIyYWE0NGY4OWU3Zjg2YzVhMzhhNzRkMDBkMDU0MzQ3MzhiZjNiNjc1ZThjZDM5MmRjOWRiMDVmM2E0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.66O_GaH4DrlOcn5loBm-fki8cl0Gf8ejAJ1bIlnffZU) 师兄您好，我在跑您的segmamba代码时，跑完了到最后一点的时候报错了，显示如下，但是他也正常保存权重文件，我之后又拿这个权重文件去跑了predict，分割结果也有，但是无法覆盖在原图像上，并且尺寸也不一样，原图像时240_240_155，分割结果的尺寸是240_155_3，请问这是哪里出错了呢，是因为我的服务器的显卡不太行吗，导致后台工作线程终止

我想请问 你是训练1000个epoch 前100个epoch dice变化明显吗

**Comment by princerice** [comment]
> ![1dd7d4c19b7aa5e4f8e8835ccd3caf1](https://private-user-images.githubusercontent.com/171776643/337071860-37b01411-b723-401f-acc7-8d58428063ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0MTQwMDMsIm5iZiI6MTcxODQxMzcwMywicGF0aCI6Ii8xNzE3NzY2NDMvMzM3MDcxODYwLTM3YjAxNDExLWI3MjMtNDAxZi1hY2M3LThkNTg0MjgwNjNiYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNVQwMTA4MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOWU4NmQ3N2NmMTRmOGYxYzBhMjJkZGFmNDMzODVlYjE5YTNkOTY3ZjMwZjE0YTY3OTE4ZmE4NmFiNzc0MGZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ULEhsEVL0P3uZHNZjJVoOvtUWlufa6bkuVmMMvWKxp8) ![297d574afdb0e42db35a34d7cb87364](https://private-user-images.githubusercontent.com/171776643/337071865-df309cf8-6cd3-4676-8b1a-8836f386b687.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0MTQwMDMsIm5iZiI6MTcxODQxMzcwMywicGF0aCI6Ii8xNzE3NzY2NDMvMzM3MDcxODY1LWRmMzA5Y2Y4LTZjZDMtNDY3Ni04YjFhLTg4MzZmMzg2YjY4Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNVQwMTA4MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zY2ZmM2Y4M2Y4OTA3NTU2YTU3NmU3MTk4ZDU0OTIxMzMwYWY3OWY0OGViN2ZmMmZiZjhmZjU3YWM3ZDgxN2U0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.shTRtS65towoiy-V4R8k8jjn74LVtfEU1JVf6TN3MYs) ![aba5f94b33941ab506c81ac7237d5d0](https://private-user-images.githubusercontent.com/171776643/337071868-0eecdd4c-1796-4f44-a542-dd55ae40a209.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0MTQwMDMsIm5iZiI6MTcxODQxMzcwMywicGF0aCI6Ii8xNzE3NzY2NDMvMzM3MDcxODY4LTBlZWNkZDRjLTE3OTYtNGY0NC1hNTQyLWRkNTVhZTQwYTIwOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNVQwMTA4MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNGQ2NzgzYmNjNDVlNjJmZmM4NjM2NWZkM2UzZWZjOTQwNzkxODAyYWRhYzhjOTMzNTRjNGU0NzJhZDZmMDgzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pAmFTjHqDL-TWgJ_yXZGPxg_U4nqGmO9FNYSELXB4ZU) ![d865c29c2ee1ce08b51eba5225063c0](https://private-user-images.githubusercontent.com/171776643/337071871-aee6e34f-0dc9-4151-b677-13f1652162ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0MTQwMDMsIm5iZiI6MTcxODQxMzcwMywicGF0aCI6Ii8xNzE3NzY2NDMvMzM3MDcxODcxLWFlZTZlMzRmLTBkYzktNDE1MS1iNjc3LTEzZjE2NTIxNjJmZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNVQwMTA4MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOGM3NmNiOTA3ZDcxZmNmNzJhZWFjNTRmYmNjYTcyOGYxMzNmZGE0ZjhhYTZkZWRkZTljMjFhOTJhOGQzMDJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5ns3fWJfmQgCoyQ7E_FJAE7YeF7QG2peHoj-qFiLodk) ![dcb2999ac1b31616d1f216ec7826b16](https://private-user-images.githubusercontent.com/171776643/337071873-df72afd4-e419-45a5-85bd-32544812752b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0MTQwMDMsIm5iZiI6MTcxODQxMzcwMywicGF0aCI6Ii8xNzE3NzY2NDMvMzM3MDcxODczLWRmNzJhZmQ0LWU0MTktNDVhNS04NWJkLTMyNTQ0ODEyNzUyYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNVQwMTA4MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YWFmNzExNDY2Mjc2NTY0MTNjODRlMThlMjEzMjdhMGE3ZmRmM2ZhYjMxZmZiNWM0ZTUzYzdmNTBmMTVmN2UxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1FdcX558PVboau5OJJB5Hb70rohhdYYP8RxhT1__FK8)师兄您好，我在跑您的segmamba代码时，跑完了到最后一点的时候报错了，显示如下，但是他也正常保存权重文件，我之后又拿这个权重文件去跑了predict，分割结果也有，但是无法覆盖在原图像上，并且尺寸也不一样，原图像时240_240_155，分割结果的尺寸是240_155_3，请问这是哪里出错了呢，是因为我的服务器的显卡不太行吗，导致后台工作线程终止

我想请问你是训练了1000个epoch吗 前100个epoch dice变化明显吗？

**Comment by NetfriendT** [comment]
![1718415148080](https://github.com/ge-xing/SegMamba/assets/171776643/fda71567-044e-4f1d-b0fc-449e218012f4)
w
![1718415148089](https://github.com/ge-xing/SegMamba/assets/171776643/766e9632-f917-4b60-b737-22790da679e5)
我
![1718415148095](https://github.com/ge-xing/SegMamba/assets/171776643/920937f2-027b-49b0-8511-86c57247155f)
gan'ju
![1718415148100](https://github.com/ge-xing/SegMamba/assets/171776643/253f61d7-2509-4bb2-b6e9-71755db9e2bd)
感觉变化还是比较明显吧

**Comment by princerice** [comment]
> ![1718415148080](https://private-user-images.githubusercontent.com/171776643/339939945-fda71567-044e-4f1d-b0fc-449e218012f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0MTU1ODcsIm5iZiI6MTcxODQxNTI4NywicGF0aCI6Ii8xNzE3NzY2NDMvMzM5OTM5OTQ1LWZkYTcxNTY3LTA0NGUtNGYxZC1iMGZjLTQ0OWUyMTgwMTJmNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNVQwMTM0NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04Zjc4YmI0Zjk2NWE5MmNkMWQ2MTA2N2Q1OWY2OGMzYTY3NGM2MDY1N2NhYjkzZTMxMzgzOTY3NGViMmQxYjg5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.M63Ze9mJrD0sp5vX4Wu6OHS_a3-t8n0JnLIFD9kuwS0) w ![1718415148089](https://private-user-images.githubusercontent.com/171776643/339939947-766e9632-f917-4b60-b737-22790da679e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0MTU1ODcsIm5iZiI6MTcxODQxNTI4NywicGF0aCI6Ii8xNzE3NzY2NDMvMzM5OTM5OTQ3LTc2NmU5NjMyLWY5MTctNGI2MC1iNzM3LTIyNzkwZGE2NzllNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNVQwMTM0NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNGVmNTI5MjYxOWNiMjQxOGEwMTkwNDI0ZGQ0MmUzYWExZmNkNjVhMmNmNjQ3NmRlNjllYTFjOTI1M2EyNDA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ykh4ovEg_RuQK29hsCnLZ20R_VN0ewDHH2kOSGi5lfo) 我 ![1718415148095](https://private-user-images.githubusercontent.com/171776643/339939948-920937f2-027b-49b0-8511-86c57247155f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0MTU1ODcsIm5iZiI6MTcxODQxNTI4NywicGF0aCI6Ii8xNzE3NzY2NDMvMzM5OTM5OTQ4LTkyMDkzN2YyLTAyN2ItNDliMC04NTExLTg2YzU3MjQ3MTU1Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNVQwMTM0NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NzgwYzA2NGE3NTc5NzVmZDE4MTJlMzZkZGNkMDVhYTMxMjhmYjE5MGNkMTI3ZjVkMjZlNmM2MGViZThlNzhiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VWTQj774KcgRjf_Dw_mvhUK3xBHNrK4FNGVftpl6Vh0) gan'ju ![1718415148100](https://private-user-images.githubusercontent.com/171776643/339939949-253f61d7-2509-4bb2-b6e9-71755db9e2bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0MTU1ODcsIm5iZiI6MTcxODQxNTI4NywicGF0aCI6Ii8xNzE3NzY2NDMvMzM5OTM5OTQ5LTI1M2Y2MWQ3LTI1MDktNGJiMi1iNmU5LTcxNzU1ZGI5ZTJiZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNVQwMTM0NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMmE4NjE3MjFjNTUxN2E2Y2JhODYwZTQ5NDNiYmVmNzRhOGYwNjY0NWM2MDI3NmNlNTZlNDRhNDc3ZTE2MDhhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DQxMnx9ytNpCrH6oVlgNjn8WhZrXh3Eyj3kBPDkLsE8) 感觉变化还是比较明显吧

我训练前50轮次 dice一直在5%左右 感觉好像是哪里设置不太对呢

**Comment by NetfriendT** [comment]
感觉按部就班的话，没有几个需要修改的地方，无非就是改几个地址，我最多就是修改了一下线程，虽然还是报错了。但是模型文件还是保存下来了
![11111](https://github.com/ge-xing/SegMamba/assets/171776643/86a2f13f-9307-4c17-a3ff-63965be6e964)

**Comment by princerice** [comment]
> 感觉按部就班的话，没有几个需要修改的地方，无非就是改几个地址，我最多就是修改了一下线程，虽然还是报错了。但是模型文件还是保存下来了 ![11111](https://private-user-images.githubusercontent.com/171776643/339940990-86a2f13f-9307-4c17-a3ff-63965be6e964.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0MTYzMDMsIm5iZiI6MTcxODQxNjAwMywicGF0aCI6Ii8xNzE3NzY2NDMvMzM5OTQwOTkwLTg2YTJmMTNmLTkzMDctNGMxNy1hM2ZmLTYzOTY1YmU2ZTk2NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNVQwMTQ2NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YWZkYjk1ZDY1ODM5NTE3Yjk3ZDQzZGE4NmE3MTUzZGQ2NWMwMzI2ZmJjMWZkOWI0Zjg5ZmNhNDU4ZDg3NmFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wOqpTGSAA7vuD5j5VbpVEVIJQ0017vuUsLhdQytJp60)

是这样的 我用的是21年的数据 对应的内容也改好了 但是dice一直很低 没超过0.1 看了你的结果作者的模型性能肯定是没问题的 ，我再调整下代码参数 感谢！可否留个微信 沟通请教一下

**Comment by princerice** [comment]
> 感觉按部就班的话，没有几个需要修改的地方，无非就是改几个地址，我最多就是修改了一下线程，虽然还是报错了。但是模型文件还是保存下来了 ![11111](https://private-user-images.githubusercontent.com/171776643/339940990-86a2f13f-9307-4c17-a3ff-63965be6e964.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0MTc0ODksIm5iZiI6MTcxODQxNzE4OSwicGF0aCI6Ii8xNzE3NzY2NDMvMzM5OTQwOTkwLTg2YTJmMTNmLTkzMDctNGMxNy1hM2ZmLTYzOTY1YmU2ZTk2NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNVQwMjA2MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMmMyNTM2M2QxZjFmYTc0NTA4MDRhNWJmZDZkOWQ5ODFlODU1MGY4NGQxZmI5ZjQ2OWE1MzkwYzRlMzA1MWU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JcaM73zSxFStG7eXpMO0_JvMPKQDW14vUO6ah_OW1-I)

我的微信是Prince_rice
