### ISSUE TITLE
BraTS2019问题

### ISSUE THREAD

**Issue by Divine0719** [ge-xing/SegMamba#36]
想请教您一下关于2019这个数据集，他和2023最大的区别就是他有4个种类，,2_preprocessing_mri.py中需要怎么改动，我目前直接跑虽然跑通了，代码运行时会报错，排查后原因就是数据集问题

**Comment by ge-xing** [comment]
你需要贴一下报错，我帮你看看吧

**Comment by Divine0719** [comment]
下图是我用默认的数据预处理得到的图像尺寸，和2023的输入输出一致
![1717810707241](https://github.com/ge-xing/SegMamba/assets/77132276/9ddda982-1390-4373-acc1-1c2902649913)
我对模型输入也进行了显示，都正常
![1717810867354](https://github.com/ge-xing/SegMamba/assets/77132276/7e69c961-846a-4aeb-9281-f09b5b870c2b)
![1717810935447](https://github.com/ge-xing/SegMamba/assets/77132276/c0e6caa1-2311-4122-891e-211328552c3e)
但是计算loss时候报错了
![1717810966321](https://github.com/ge-xing/SegMamba/assets/77132276/cb6d12ef-86dd-4b5c-baeb-3c9f804183f0)
我在想是不是BtrTS2019的标签列别有4类的问题导致的，但是不知道怎么修改预处理的代码
有劳您帮忙看下，不甚感激

**Comment by ge-xing** [comment]
是的，应该是标签问题导致的，brats19的话，标签是[0, 1, 2, 4]。所以你在训练的代码里面，当拿到labels的时候，你需要用：

labels[labels == 4] = 3

这样把标签设置为 0, 1, 2, 3 即可。

**Comment by Divine0719** [comment]
已解决！万分感谢！
