### ISSUE TITLE
分割代码的参数问题

### ISSUE THREAD

**Issue by NetfriendT** [ge-xing/SegMamba#45]
师兄您好，我在更换数据集的时候，在4_predicate遇到了以下问题。首先我使用的数据集的Unique label values: [0 1 2 3]和Bra的[0. 1. 2. 3.]不太一样，另外我的想法是不需要区分病理区域，所以我把result = [(labels == 1) | (labels == 3), (labels == 1) | (labels == 3) | (labels == 2), labels == 3]全部修改为result = [(labels == 1), (labels == 2), (labels == 3)]。

    在4_predicate的83行左右出现了错误，model_output = predictor.predict_raw_probability(model_output,properties=properties)调用了light_train文件predication49行左右
    d, w, h = shape_after_cropping_before_resample[0].item(),shape_after_cropping_before_resample[1].item(), shape_after_cropping_before_resample[2].item()。
    d, w, h获取的properties["shape_after_cropping_before_resample"]数值为[tensor([9]), tensor([216]), tensor([256])]，导致Model output shape after conversion: torch.Size([3, 9, 216, 256])。这导致d = dice(output_i, label_i)无法计算，因为label的后三维是 (90, 321, 380)。
    跑Bra的数据集时，[tensor([146]), tensor([179]), tensor([134])]和Model output shape: torch.Size([1, 4, 146, 179, 134])后三维一致所以成功运行。我感觉问题是properties["shape_after_cropping_before_resample"]的properties里面的数据有问题，是不是我第二步的预处理出现了问题呢？
![1](https://github.com/user-attachments/assets/b33bc5d3-95b7-4ac1-bc69-ca57ad6077f9)
![2](https://github.com/user-attachments/assets/167fc07d-aa9e-4658-ae28-5ab4a5f75425)
![3](https://github.com/user-attachments/assets/bf19c4d3-580d-4395-89da-32d7f3452706)
![4](https://github.com/user-attachments/assets/d1c2b449-ba40-44cd-a074-46d66f253529)

**Comment by NetfriendT** [comment]
此外由于我只使用了一个输入图像和一个标签，所以我的segmamba输入通道是1，输出通道是4
![Uploading 1720778735687.png…]()

**Comment by ge-xing** [comment]
crop 是把背景区域（image==0）给去掉，你检查下crop部分有没有问题，比如crop是不是把前景也给crop掉了？

**Comment by NetfriendT** [comment]
> crop 是把背景区域（image==0）给去掉，你检查下crop部分有没有问题，比如crop是不是把前景也给crop掉了？

不过训练都完成了，也会有问题吗

**Comment by ge-xing** [comment]
你可以可视化一下 看看具体结果是什么

**Comment by ge-xing** [comment]
慢慢debug一下 不行的话加我微信说吧 最近在外面开会
