### ISSUE TITLE
最后解码器out的输出问题

### ISSUE THREAD

**Issue by wanjianxu** [ge-xing/SegMamba#46]
您好，最后的解码器out设定outchannel为13不是很能理解，不应该是4吗，分割背景，WT,ET,TC，四个部分？有点菜刚接触，是否我理解的有偏颇，调试过程中发现分割的结果又4个通道是为什么，不应该是和标签label一致只有一个通道吗，感谢您的指导
![78BGELLK`I SCKOHWKRM`LE](https://github.com/user-attachments/assets/1811cde6-2b92-4c78-9ef2-34a250ed86a2)
![BI7WW8`(7}ID5G69%ZGU8 7](https://github.com/user-attachments/assets/ec816b2c-487f-4a1b-a557-9af3fd267677)

**Comment by ge-xing** [comment]
这个是函数定义部分的一个默认参数值为13，最后的结果是要看你传入了什么值到这个函数。
