### ISSUE TITLE
Missing residual connections in Mamba Block

### ISSUE THREAD

**Issue by BailiangJ** [ge-xing/SegMamba#5]
![image](https://github.com/ge-xing/SegMamba/assets/33227998/4f49af78-cd01-4492-af8a-97dcc4e7c70e)

Hi @ge-xing , thanks a lot for sharing the code.

I have a few questions.

1. In the figure above, there are two residual connections  in the MambaBlock,

However, in the implementation [code](https://github.com/ge-xing/SegMamba/blob/5c32a2d8fed12e230e1f54a5e839a7ec1e67e447/model_segmamba/segmamba.py#L133) the residual connections are missing. Is it intended?

2. In the [MambaEncoder](https://github.com/ge-xing/SegMamba/blob/5c32a2d8fed12e230e1f54a5e839a7ec1e67e447/model_segmamba/segmamba.py#L124) only the `x_out` will goes through the MLP layer **''Mamba->LN->MLP''** while `x` will skip the MLP and continues **''Mamba->LN->downsizeConv''**. Why would this be?

Thanks a lot for your help.

**Comment by ge-xing** [comment]
The code version is old, I will update it recently along with the paper. Thank you.
