### ISSUE TITLE
Requirement file

### ISSUE THREAD

**Issue by hcorbaz** [ge-xing/SegMamba#6]
Hello,

Your project looks really interesting and I am willing to try it. However, I struggle with the installation: the way you suggest doesn't work for me. I encounter a lot of compatibility issues.
Would it be possible to share you exact cuda version, nvcc and c++ compiler version and a detailed requirement file?

Thanks a lot

**Comment by Devil-Ideal** [comment]
> Hello,
> 
> Your project looks really interesting and I am willing to try it. However, I struggle with the installation: the way you suggest doesn't work for me. I encounter a lot of compatibility issues. Would it be possible to share you exact cuda version, nvcc and c++ compiler version and a detailed requirement file?
> 
> Thanks a lot

Have you solved this problem? I also encountered the same mistake.
