### ISSUE TITLE
Seeking Guidance and Assistance with SegMamba for Liver Tumor Segmentation

### ISSUE THREAD

**Issue by koukihk** [ge-xing/SegMamba#9]
Hello,

Thank you for your work! I attempted to use the SegMamba model from your code for segmenting single-channel 3D liver tumors. However, when testing on the same dataset, the dice were slightly inferior (approximately 6%) compared to UNETR, SwinUNETR, and SwinUNETR-V2.

As a novice researcher, I am eager to receive your guidance and assistance. I suspect that there might be suboptimal parameter settings during training or other reasons contributing to this discrepancy. Could you please share some insights and suggestions based on your experience? I would greatly appreciate your help.

**Comment by ge-xing** [comment]
I am happy to conduct the experiments on your dataset. Could you mind to share your dataset and data split with me?

**Comment by koukihk** [comment]
> I am happy to conduct the experiments on your dataset. Could you mind to share your dataset and data split with me?

The dataset I used for testing is LiTS2017, which can be obtained at https://competitions.codalab.org/competitions/17094. This dataset comprises a total of 131 samples, with approximately 13 samples lacking tumors. During the testing process, I randomly selected 22 samples with tumors for evaluation.

**Comment by ge-xing** [comment]
Could you add my wechat to help you check the evaluation process? 18340097191

**Comment by koukihk** [comment]
> Could you add my wechat to help you check the evaluation process? 18340097191

I'd be happy to. I'll add you on WeChat when I have some free time later. Thank you for your guidance!

**Comment by ge-xing** [comment]
Thank you for your attention~ I am also downloading the dataset you mentioned. I will give you feedback as soon as possible.
